In [1]:
!pip install scikit-surprise

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.0/772.0 kB 5.5 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.3-cp311-cp311-macosx_10_9_x86_64.whl size=1116811 sha256=6f84e470c628ea27f1650eb7e3424c481fbfec686eeb47f62df6c74c5366401a
  Stored in directory: /Users/riteshsengar/Library/Caches/pip/wheels/f4/2b/26/e2a5eae55d3b7688995e66abe7f40473aac6c95ddd8ee174a8
Successfully built scikit-surprise


In [5]:
!pip install scipy

In [1]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix, coo_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import NearestNeighbors
from scipy.sparse.linalg import svds
from sklearn.decomposition import NMF
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


In [2]:
df = pd.read_csv("selected_item_based.csv")
df = df.drop("Unnamed: 0", axis=1)
df.head()

asin  overall      reviewerID
0  073530498X        4  A3VVMIMMTYQV5F
1  073530498X        5  A1XSPKZ8HHSBX2
2  073530498X        5  A2ZEQ0WBLNQN7O
3  073530498X        5  A2IC3RIPB6HKSQ
4  073530498X        5  A1JHNR71TPEETW

In [2]:
from surprise import accuracy
from surprise import *
from surprise import Dataset
from surprise.model_selection import cross_validate
from surprise import Reader
import pandas as pd

# Load the data from a CSV file
df = pd.read_csv("selected_item_based.csv")
ratings = df.drop("Unnamed: 0", axis=1)
ratings.head()

# Make sure the data is clean
ratings = ratings.dropna()
ratings = ratings.drop_duplicates()

# Define a reader with the rating scale
reader = Reader(rating_scale=(1, 5))  # Assuming the ratings are from 1 to 5

# Load the data from the DataFrame into the surprise dataset
data = Dataset.load_from_df(ratings[['reviewerID', 'asin', 'overall']], reader)

In [8]:
# Choose a recommendation algorithm, here SVD is chosen
algo = SVD()

# Run 5-fold cross-validation and print results
results = cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

print("Test RSME : ",results['test_rmse'].mean())
print("Test MAE : ",results['test_mae'].mean())
print("*"*100)
print()

import pickle

pickle.dump(model, "model.p")

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    1.0699  1.0715  1.0702  1.0638  1.0723  1.0695  0.0030  
MAE (testset)     0.7887  0.7896  0.7900  0.7859  0.7915  0.7891  0.0019  
Fit time          10.54   10.07   10.07   10.15   10.39   10.24   0.19    
Test time         1.22    1.17    1.50    1.25    1.17    1.26    0.12    
Test RSME :  1.069533391143529
Test MAE :  0.789116349337084
****************************************************************************************************



In [9]:
algo = NMF()

# Run 5-fold cross-validation and print results
results = cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

print("Test RSME : ",results['test_rmse'].mean())
print("Test MAE : ",results['test_mae'].mean())
print("*"*100)
print()

Evaluating RMSE, MAE of algorithm NMF on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    1.2658  1.2656  1.2738  1.2653  1.2638  1.2669  0.0035  
MAE (testset)     0.9644  0.9647  0.9703  0.9661  0.9627  0.9656  0.0026  
Fit time          45.67   34.19   35.91   33.84   32.71   36.46   4.72    
Test time         1.30    1.00    1.39    1.19    0.91    1.16    0.18    
Test RSME :  1.2668602920201608
Test MAE :  0.9656349440675184
****************************************************************************************************



In [3]:
algo = NormalPredictor()

# Run 5-fold cross-validation and print results
results = cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

print("Test RSME : ",results['test_rmse'].mean())
print("Test MAE : ",results['test_mae'].mean())
print("*"*100)
print()

Evaluating RMSE, MAE of algorithm NormalPredictor on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    1.4625  1.4661  1.4585  1.4588  1.4626  1.4617  0.0028  
MAE (testset)     1.0778  1.0788  1.0736  1.0747  1.0766  1.0763  0.0019  
Fit time          0.73    0.88    0.93    0.90    0.92    0.87    0.07    
Test time         0.89    1.26    0.78    0.81    0.57    0.86    0.23    
Test RSME :  1.4617076013325963
Test MAE :  1.07631548618996
****************************************************************************************************



In [4]:
algo = CoClustering()

# Run 5-fold cross-validation and print results
results = cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

print("Test RSME : ",results['test_rmse'].mean())
print("Test MAE : ",results['test_mae'].mean())
print("*"*100)
print()

Evaluating RMSE, MAE of algorithm CoClustering on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    1.1846  1.1787  1.1932  1.1952  1.1961  1.1896  0.0068  
MAE (testset)     0.7950  0.7912  0.8006  0.8026  0.8036  0.7986  0.0048  
Fit time          32.19   31.27   32.18   33.54   35.97   33.03   1.64    
Test time         1.05    0.65    0.68    1.00    1.15    0.91    0.20    
Test RSME :  1.1895655174265356
Test MAE :  0.7985863689607413
****************************************************************************************************



In [5]:
algo = BaselineOnly()

# Run 5-fold cross-validation and print results
results = cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

print("Test RSME : ",results['test_rmse'].mean())
print("Test MAE : ",results['test_mae'].mean())
print("*"*100)
print()

Estimating biases using als...
Estimating biases using als...
Estimating biases using als...
Estimating biases using als...
Estimating biases using als...
Evaluating RMSE, MAE of algorithm BaselineOnly on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    1.0754  1.0721  1.0726  1.0776  1.0781  1.0752  0.0025  
MAE (testset)     0.8050  0.8025  0.8029  0.8055  0.8068  0.8045  0.0016  
Fit time          3.71    3.75    3.79    3.91    3.94    3.82    0.09    
Test time         0.90    0.99    0.61    0.59    0.89    0.80    0.16    
Test RSME :  1.0751596069329166
Test MAE :  0.8045472222951477
****************************************************************************************************



In [6]:
algo = SlopeOne()

# Run 5-fold cross-validation and print results
results = cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

print("Test RSME : ",results['test_rmse'].mean())
print("Test MAE : ",results['test_mae'].mean())
print("*"*100)
print()

Evaluating RMSE, MAE of algorithm SlopeOne on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    1.2457  1.2438  1.2462  1.2441  1.2450  1.2450  0.0009  
MAE (testset)     0.8418  0.8402  0.8433  0.8408  0.8402  0.8412  0.0012  
Fit time          7.78    8.46    8.13    8.45    8.34    8.23    0.25    
Test time         1.88    1.41    1.76    1.71    1.80    1.71    0.16    
Test RSME :  1.2449567778500819
Test MAE :  0.8412318466998594
****************************************************************************************************



In [ ]:
# Not able to compute completely and system get restarted or instance get terminated before completing the training of the system

# algo = KNNBasic()

# # Run 5-fold cross-validation and print results
# results = cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

# print("Test RSME : ",results['test_rmse'].mean())
# print("Test MAE : ",results['test_mae'].mean())
# print("*"*100)
# print()

In [3]:
count = df.groupby("asin", as_index=False)["overall"].count()

df1 = pd.merge(df, count, how='right', on=['asin'])
df1.head()

df1 = df1.rename(columns = {"overall_y" : "totalReviewers", "overall_x": "user_rating"})
# df1.reset_index(drop=True, inplace=True)
df1.head()

df1 = df1.sort_values(by='totalReviewers', ascending=False)
dfCount = df1[df1.totalReviewers >= 50]
dfCount.head()

len(dfCount.reviewerID.unique())

reviewer_data = {id: index+1 for index, id in enumerate(dfCount.reviewerID.unique())}
reviewer_data

asin_data = {id: index+1 for index, id in enumerate(dfCount.asin.unique())}

dfCount["user_id"] = dfCount["reviewerID"].apply(lambda x: reviewer_data[x]).astype(int)
dfCount["item_id"] = dfCount["asin"].apply(lambda x: asin_data[x]).astype(int)
dfCount.head()

df_filter = dfCount[["user_id", "item_id", "user_rating", "totalReviewers"]]
df_filter.head()

/var/folders/d9/38d01fms6l33ty3q2_t8jtj40000gn/T/ipykernel_1040/296555971.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCount["user_id"] = dfCount["reviewerID"].apply(lambda x: reviewer_data[x]).astype(int)
/var/folders/d9/38d01fms6l33ty3q2_t8jtj40000gn/T/ipykernel_1040/296555971.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCount["item_id"] = dfCount["asin"].apply(lambda x: asin_data[x]).astype(int)


user_id  item_id  user_rating  totalReviewers
16387        1        1            3            4531
10717        2        2            5            4531
10704        3        2            5            4531
10705        4        2            4            4531
10706        5        2            5            4531

In [4]:
n_users = df_filter.user_id.unique().shape[0]
n_items = df_filter.item_id.unique().shape[0]
n_items = df_filter['item_id'].max()
A = np.zeros((n_users,n_items))
for line in df_filter.itertuples():
    A[line[1]-1,line[2]-1] = line[3]
    
print("Original rating matrix : ",A)

Original rating matrix :  [[3. 3. 3. ... 0. 0. 0.]
 [5. 5. 5. ... 0. 0. 0.]
 [5. 5. 5. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
train_data, test_data = train_test_split(A, test_size=0.2, random_state=42)

In [6]:
def calculate_item_differences(user_item_matrix):
    item_diff = {}
    for item1 in range(user_item_matrix.shape[1]):
        item_diff[item1] = {}
        for item2 in range(user_item_matrix.shape[1]):
            common_users = np.where(np.logical_and(user_item_matrix[:, item1] > 0, user_item_matrix[:, item2] > 0))
            if len(common_users[0]) > 0:
                diff = user_item_matrix[common_users, item1] - user_item_matrix[common_users, item2]
                item_diff[item1][item2] = np.mean(diff)
    return item_diff

def predict_ratings(train_data, item_diff):
    predicted_ratings = np.zeros_like(train_data, dtype=float)
    for user in range(train_data.shape[0]):
        for item in range(train_data.shape[1]):
            if train_data[user, item] == 0:
                item_ratings = train_data[:, item]
                common_users = np.where(item_ratings > 0)
                if len(common_users[0]) > 0:
                    predicted_ratings[user, item] = np.mean([train_data[user, item] + item_diff[item][i] for i in common_users[0]])
    return predicted_ratings


In [ ]:
predicted_ratings = predict_ratings(train_data, calculate_item_differences(A))
predicted_ratings.shape

In [ ]:
mse = mean_squared_error(test_data[test_data > 0], predicted_ratings[test_data > 0])
mse